name: Update Algolia Search Index

on:
  push:
    branches:
      - main
    paths:
      - "content/**"
  workflow_dispatch:

jobs:
  algolia-atomic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: Build site
        run: |
          npm install
          hugo

      - name: Upload Algolia index
        env:
          ALGOLIA_APP_ID: ERTFAVWBRS
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX_NAME: acuherb
          ALGOLIA_INDEX_FILE: ./public/search.json
        run: |
          npm run algolia
